# YAML EXPLANATION FILE #

Name: Mr.54nDr0x404
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++
Python-Version: Python3 
Author: Muh Ikhsan M
Copyright: (C) 2021-2022 Ikhsan
Project-site: https://muhikhsanm404.github.io/
Download: https://github.com/muhikhsanm404/osint
Platforms: Linux/MacOS/Termux/Windows
Version: Nuke1.0.1(V6)git
License: GNU General Public License v3.0
